### ISSUE TITLE
Fix contacts div

### ISSUE THREAD

**Issue by SnowyCoder** [SnowyCoder/snowycoder.github.io#1]
The contacts are ovals and not circles

**Comment by kev1nboer** [comment]
Hi @SnowyCoder, I will have a look!

**Comment by kev1nboer** [comment]
PR added: #2

**Comment by BhathiyaTK** [comment]
Made PR: #3

**Comment by SnowyCoder** [comment]
Issued closed with PR #2 and merged in 0550709094e816881c4708fd5e69d1094c1a9f74.
Thanks guys!
